### ISSUE TITLE
Week 9 - Create Task Check

### ISSUE THREAD

**Issue by nicm2** [yqw7/dominators#72]
**Tasks**

- [ ] 4.1- 4.3 Journal Video Notes and Quizzes/Corrections  1pt
- [ ] PBL Final Summary - plan for 3 weeks and look ahead to Weeks 10 and 11.
- [ ] An individual/pair wiki page with the description and outline of the Create Performance Task. 5 pts

**Create Task**

-Final program code (created independently or collaboratively) 
-A video that displays the running of your program and demonstrates functionality you developed (created independently) 
-Written responses to all the prompts in the performance task (created independently)
- [CB Requirements](https://apcentral.collegeboard.org/pdf/ap-csp-student-task-directions.pdf?course=ap-computer-science-principles)
